name: women_health
description: "A new Flutter project."

# Prevents accidental publishing to pub.dev
publish_to: 'none'

# Versioning for your application
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI and Navigation
  cupertino_icons: ^1.0.8
  google_nav_bar: ^5.0.7
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17
  hugeicons: ^0.0.7
  flutter_screenutil: ^5.9.3

  # State Management
  get: ^4.6.6

  # Networking
  http: ^1.3.0

  # Storage & Preferences
  shared_preferences: ^2.5.2

  # Widgets & Utilities
  menstrual_cycle_widget: ^3.2.0
  step_progress_indicator: ^1.0.2
  heroicons: ^0.11.0
  pin_code_fields: ^8.0.1
  intl: ^0.19.0
  image_picker: ^1.1.2
  mime_type: ^1.0.1
  url_launcher: ^6.3.1
  easy_localization: ^3.0.7+1
  custom_refresh_indicator: ^4.0.1
  onesignal_flutter: ^5.3.0
  # google_mobile_ads: ^5.3.1
  font_awesome_flutter: ^10.8.0
  cached_network_image: ^3.4.1
  easy_image_viewer: ^1.5.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lang/en.json
    - assets/lang/bn.json
